# Generated by Django 3.2.13 on 2022-06-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=500)),
                ('ContactNumber', models.CharField(max_length=500)),
                ('EmailId', models.CharField(max_length=500)),
                ('Password', models.CharField(max_length=500)),
                ('DateOfBirth', models.DateField()),
                ('MarkForDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
