# Generated by Django 4.0.3 on 2022-06-05 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mesa', '0002_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ContactNumber',
            new_name='contactNumber',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='DateOfBirth',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='EmailId',
            new_name='emailId',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='MarkForDelete',
            new_name='markForDelete',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserId',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserName',
            new_name='userName',
        ),
    ]
