# Generated by Django 4.0.3 on 2022-06-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mesa', '0003_rename_contactnumber_user_contactnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummText',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
