# Generated by Django 4.0.3 on 2022-06-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mesa', '0004_summtext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SummText',
        ),
    ]
